/* Generated by tools/gen_assets.py - do not edit by hand. */
#ifndef ASSETS_H
#define ASSETS_H
#include <stdint.h>

#define T_BLANK 0
#define T_SOLID1 1
#define T_SOLID2 2
#define T_SOLID3 3
#define T_DITH01 4
#define T_DITH12 5
#define T_DITH23 6
#define T_CARD_TL 7
#define T_CARD_T 8
#define T_CARD_TR 9
#define T_CARD_L 10
#define T_CARD_FACE 11
#define T_CARD_R 12
#define T_CARD_BL 13
#define T_CARD_B 14
#define T_CARD_BR 15
#define T_SHP_CIR 16
#define T_SHP_SQR 17
#define T_SHP_TRI 18
#define T_SHP_DIA 19
#define T_ICO_MOVE 20
#define T_ICO_FIGHT 21
#define T_ICO_SNEAK 22
#define T_ICO_SPEAK 23
#define T_ICO_TAKE 24
#define T_ICO_GIVE 25
#define T_PIP2 26
#define T_PIP4 27
#define T_PIP6 28
#define T_PIP8 29
#define T_WEAVE_A 30
#define T_WEAVE_B 31
#define T_WIN_TL 32
#define T_WIN_T 33
#define T_WIN_TR 34
#define T_WIN_L 35
#define T_WIN_R 36
#define T_WIN_BL 37
#define T_WIN_B 38
#define T_WIN_BR 39
#define T_HEART 40
#define T_HEART_E 41
#define T_ICO_DECK 42
#define T_FLAG 43
#define T_FLAG_DONE 44
#define T_STAR1 45
#define T_STAR2 46
#define T_MOON 47
#define T_ROCK 48
#define T_ROCK_L 49
#define T_ROCK_R 50
#define T_SNOW 51
#define T_SNOW_L 52
#define T_SNOW_R 53
#define T_SNOWCAP 54
#define T_TREE_TOP 55
#define T_TREE_BOT 56
#define T_PATHDOT 57

#define FONT_BASE 58
#define FONT_COUNT 48
#define BG_TILE_COUNT 106

#define S_ARROW_UP 0
#define S_ARROW_RT 1
#define S_CLIMBER_A 2
#define S_CLIMBER_B 3
#define S_SPARKLE 4
#define SPR_TILE_COUNT 5

extern const uint8_t bg_tiles[];
extern const uint8_t spr_tiles[];
extern const uint8_t font_chars[];
#endif
